
// Depositbk1.js - polished for production (Firebase v8).
// IMPORTANT: Replace firebaseConfig with your project's config values.

// ---- Firebase configuration: REPLACE THESE VALUES ----
const firebaseConfig = {
  apiKey: "REPLACE_WITH_YOUR_API_KEY",
  authDomain: "REPLACE_WITH_YOUR_AUTH_DOMAIN",
  projectId: "REPLACE_WITH_YOUR_PROJECT_ID",
  storageBucket: "REPLACE_WITH_YOUR_STORAGE_BUCKET",
  messagingSenderId: "REPLACE_WITH_YOUR_MESSAGING_SENDER_ID",
  appId: "REPLACE_WITH_YOUR_APP_ID"
};
// -----------------------------------------------------

if (!firebase.apps.length) {
  firebase.initializeApp(firebaseConfig);
} else {
  firebase.app();
}
const auth = firebase.auth();
const db = firebase.firestore();

// UI elements
const canvas = document.getElementById('canvas');
const ctx = canvas.getContext('2d');
const downloadBtn = document.getElementById('downloadBtn');
const saveBtn = document.getElementById('saveBtn');
const loginBtn = document.getElementById('loginBtn');
const logoutBtn = document.getElementById('logoutBtn');

function drawPreview(){
  // Clear
  ctx.fillStyle = '#ffffff';
  ctx.fillRect(0,0,canvas.width,canvas.height);

  // Header band
  ctx.fillStyle = '#0b84ff';
  ctx.fillRect(0,0,canvas.width,120);

  // Title text
  ctx.fillStyle = '#ffffff';
  ctx.font = '40px Kanit, sans-serif';
  ctx.fillText('แจ้งเงินเข้า', 32, 70);

  // Fields from form
  const account = document.getElementById('senderaccount1').value || '-';
  const money = document.getElementById('money01').value || '-';
  const datetime = document.getElementById('datetime').value || '-';
  const receiver = document.getElementById('receiver').value || '-';
  const timeNotify = document.getElementById('datetime_plus_one').value || '-';

  ctx.fillStyle = '#111827';
  ctx.font = '24px Kanit, sans-serif';
  ctx.fillText('บัญชี: ' + account, 36, 180);
  ctx.fillText('จำนวนเงิน: ฿' + money, 36, 220);
  ctx.fillText('เวลาเงินเข้า: ' + datetime, 36, 260);
  ctx.fillText('แจ้งเตือน: ' + timeNotify, 36, 300);
  ctx.fillText('ผู้รับ: ' + receiver, 36, 340);

  // Footer
  ctx.font = '18px Kanit, sans-serif';
  ctx.fillStyle = '#6b7280';
  ctx.fillText('Generated by Mindora • ' + new Date().toLocaleString('th-TH'), 36, canvas.height - 40);
}

function updateDisplay(){
  drawPreview();
}

function downloadImage(){
  const link = document.createElement('a');
  link.download = 'slip_' + Date.now() + '.png';
  link.href = canvas.toDataURL('image/png');
  link.click();
}

function togglePowerSavingMode(){
  const btn = document.getElementById('powerSavingMode');
  if(btn.classList.contains('active')){
    btn.classList.remove('active');
    btn.textContent = 'โหมดประหยัดพลังงาน';
    canvas.style.filter = 'none';
  } else {
    btn.classList.add('active');
    btn.textContent = 'ปิดโหมดประหยัด';
    canvas.style.filter = 'grayscale(0.6) brightness(0.9)';
  }
}

// Save data to Firestore (requires auth)
async function saveToFirestore(){
  if(!auth.currentUser){
    alert('กรุณาล็อกอินก่อนบันทึก');
    return;
  }
  const payload = {
    account: document.getElementById('senderaccount1').value,
    money: document.getElementById('money01').value,
    datetime: document.getElementById('datetime').value,
    notifyTime: document.getElementById('datetime_plus_one').value,
    receiver: document.getElementById('receiver').value,
    createdAt: firebase.firestore.FieldValue.serverTimestamp(),
    uid: auth.currentUser.uid
  };
  try{
    const docRef = await db.collection('slips').add(payload);
    alert('บันทึกสำเร็จ: ' + docRef.id);
  }catch(e){
    console.error(e);
    alert('เกิดข้อผิดพลาดในการบันทึก');
  }
}

// Simple login (popup) using Google
function loginWithGoogle(){
  const provider = new firebase.auth.GoogleAuthProvider();
  auth.signInWithPopup(provider).then(result => {
    console.log('Signed in:', result.user.displayName);
  }).catch(err => {
    console.error(err);
    alert('Login failed');
  });
}

function logout(){
  auth.signOut().then(()=>{
    console.log('Signed out');
  });
}

// Wire events
downloadBtn.addEventListener('click', downloadImage);
saveBtn.addEventListener('click', saveToFirestore);
loginBtn.addEventListener('click', loginWithGoogle);
logoutBtn.addEventListener('click', logout);
document.getElementById('slipForm').addEventListener('input', updateDisplay);

// Update UI on auth state change
auth.onAuthStateChanged(user => {
  if(user){
    loginBtn.style.display = 'none';
    logoutBtn.style.display = 'inline-block';
  } else {
    loginBtn.style.display = 'inline-block';
    logoutBtn.style.display = 'none';
  }
});

// Initial draw
updateDisplay();
